In [2]:
from transformers import BertTokenizer, BertForSequenceClassification
import pandas as pd
from transformers import pipeline
from tqdm import tqdm
import datasets

In [3]:
# Loading data
train_set = pd.read_csv("../data/twitter_training.csv",names=["Tweet Id","Entity","Sentiment","Tweet Content"])
train_set

,Tweet Id,Entity,Sentiment,Tweet Content
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
...,...,...,...,...
74677,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74678,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74679,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74680,9200,Nvidia,Positive,Just realized between the windows partition of...
74681,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [8]:
# Cleaning data
## Remove rows with missing values
hasnan=train_set.isna().any(axis=1)
droppedcount = 0
for i in hasnan.index:
    if hasnan[i]:
        print("dropped",i)
        droppedcount += 1
        train_set=train_set.drop(i)
print("Total Dropped:",droppedcount)

Total Dropped: 0

In [8]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)

In [9]:
max_len = 128
X_train_enc = tokenizer.batch_encode_plus(train_set["Tweet Content"],padding=True,truncation=True,max_length=max_len,return_tensors="pt")

In [10]:
k = 100
print('Original Tweet:',train_set["Tweet Content"][k])
print('\nInput Ids:\n',X_train_enc['input_ids'][k])
print('\nDecoded Ids -->>\n',tokenizer.decode(X_train_enc['input_ids'][k]))
print('\nAttention Mask -->>\n',X_train_enc['attention_mask'][k])
print('Sentiment:',train_set["Sentiment"][k])
print('Entity',train_set["Entity"][k])

Original Tweet: Deep Grounded almost looked pretty cool even despite the borderlands fifth tier unfunny writing format until ultimately it became yet another survival crafting mobile game. I really can ’ t wait for this shitty trend starting to... die

Input Ids:
 tensor([  101, 16764,  2471,  2001,  3492,  4658,  2130,  2750,  1996,  2327,
         7563,  4895, 11263, 10695,  2100,  3015,  2127,  2057,  2150,  2664,
         2178, 15703,  7477,  2075,  2208,  1012,  1045,  5667,  2064,  1521,
         1056,  3524,  2006,  2023, 28543,  9874,  2000,  3280,   102,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0])

Decoded Ids -->>
 [CLS] grounded almost was pretty cool even despite the top tier unfunny writing until we became yet another annoying crafting game. i seriously can ’ t wait on this shitty trend to die [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]

Attention Mask -->>
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])
Sentiment: Negative
Entity Borderlands

In [ ]:
#model = BertForSequenceClassification.from_pretrained('bert-base-uncased',num_labels=3)

In [ ]:
#optimizer = tf.keras.optimizers.Adam(learning_rate=2e-5)
#loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
#metric = tf.keras.metrics.SparseCategoricalAccuracy('accuracy')
#model.compile()

In [ ]:
#model(input_ids = X_train_enc['input_ids'], labels=train_set["Sentiment"])

In [5]:
model_p = pipeline(task='sentiment-analysis',model='bert-base-uncased',tokenizer='bert-base-uncased',framework='pt')

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Device set to use cpu

In [ ]:
#k = 7777
#print(model_p.predict(train_set["Tweet Content"][k]))
#print(train_set["Sentiment"][k])
#print(train_set["Tweet Content"][k])

In [9]:
# Loading data
test_set = pd.read_csv("../data/twitter_validation.csv",names=["Tweet Id","Entity","Sentiment","Tweet Content"])
test_set

,Tweet Id,Entity,Sentiment,Tweet Content
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...
...,...,...,...,...
995,4891,GrandTheftAuto(GTA),Irrelevant,⭐️ Toronto is the arts and culture capital of ...
996,4359,CS-GO,Irrelevant,tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
997,2652,Borderlands,Positive,Today sucked so it’s time to drink wine n play...
998,8069,Microsoft,Positive,Bought a fraction of Microsoft today. Small wins.
999,6960,johnson&johnson,Neutral,Johnson & Johnson to stop selling talc baby po...

In [8]:
# Cleaning data
## Remove rows with missing values
hasnan=test_set.isna().any(axis=1)
droppedcount = 0
for i in hasnan.index:
    if hasnan[i]:
        print("dropped",i)
        droppedcount += 1
        test_set=test_set.drop(i)
print("Total Dropped:",droppedcount)

Total Dropped: 0

In [14]:
pred = model_p.run_multi(test_set["Tweet Content"])

TypeError: Pipeline.run_multi() missing 3 required positional arguments: 'preprocess_params', 'forward_params', and 'postprocess_params'

In [16]:
test_set["Tweet Content"][0]

'I mentioned on Facebook that I was struggling for motivation to go for a run the other day, which has been translated by Tom’s great auntie as ‘Hayley can’t get out of bed’ and told to his grandma, who now thinks I’m a lazy, terrible person 🤣'

In [9]:
dataset = datasets.load_dataset("../data/clean", split="train")
                       #names=["Tweet Id","Entity","Sentiment","Tweet Content"]

In [10]:
dataset.values()

AttributeError: 'Dataset' object has no attribute 'values'